version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dockerized_rails_app
      POSTGRES_USER: aclark
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - common-net
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - common-net

volumes:
  postgres:

networks:
  common-net: {}